### ISSUE TITLE
Object Detect From Image Source

### ISSUE THREAD

**Issue by stories2** [NumericalReconstructionWithOpenCV/Calculator#2]
## Problem File Name
ObjectDetect.py
## Expected behavior
Return object detected image data
## Actual behavior
[]
## Steps to reproduce the behavior
It always happens. 
Run below test code.
`testSuite.addTest(ProjectCalculateLength('ObjectDetectFromImage'))`
## Program printed log
```
TestVersionOfOpenCV (__main__.ProjectSettingTest) ... ok
MakeBlankImage (__main__.ProjectCalculateLength) ... ok
BeforeImageLoadTest (__main__.ProjectCalculateLength) ... ok
AfterImageLoadTest (__main__.ProjectCalculateLength) ... ok
ObjectDetectFromImage (__main__.ProjectCalculateLength) ... ok

----------------------------------------------------------------------
Ran 5 tests in 0.009s

OK
```

**Comment by Asdran** [comment]
5dd787b3a295ac3c5b33c7d072663118cd003c38
문제 발생

**Comment by stories2** [comment]
505c42cf4bfe7f324d48ead874d20652fb05c369
Catched the difference of each images.
