### ISSUE TITLE
ObjectDetect.py의 Show 함수 수정 사항

### ISSUE THREAD

**Issue by dinsslug** [NumericalReconstructionWithOpenCV/Calculator#5]
## Problem File Name
ObjectDetect.py

## Expected behavior
Show 함수 호출시 창 이름을 정할 수 있도록 파라메터 추가
Show 함수 사용 시 창 이름을 변수명으로 통일
예) 'ABC'이라는 변수를 창으로 띄울때 창 이름을 'ABC'로 할 것

## Actual behavior
Show 함수의 창 이름이 image+번호로 시작됨

## Program printed log
```
Input log here
```

**Comment by stories2** [comment]
This issue solved by sunjbs
c5d3e942602c9dc32196dbe81bcedf6b710f7103
